### 상품 생성
POST http://localhost:8080/api/items/v1
Content-Type: application/json

{
  "storeId": "d088e270-7dc1-46c3-add7-ad7b654eb376",
  "itemName" : "test",
  "price": "12345",
  "description": "테스트 설명"
}

### 상품 수정
@ProductId = c8daec60-3de9-4527-9c3a-bc1390c7f966
PUT http://localhost:8080/api/items/v1/{{ProductId}}
Content-Type: application/json

{
  "itemName": "시간테스트",
  "price": 10001,
  "status": "ACTIVE",
  "description": "업데이트 시간확인"
}

### 상품 삭제(soft delete)
DELETE http://localhost:8080/api/items/v1/{{ProductId}}
Content-Type: application/json


### 상품 단일 조회(soft delete제외 확인)
GET http://localhost:8080/api/items/v1/{{ProductId}}


### 상품 전체
GET http://localhost:8080/api/items/v1

### 상품 전체 (검색 조회)
GET http://localhost:8080/api/items/v1?maxPrice=99999&page=1&size=10&storeId=d088e270-7dc1-46c3-add7-ad7b654eb376
